CREATE TABLE `my_webpages` (
        `ID` INT(11) NOT NULL AUTO_INCREMENT,
        `TITLE` VARCHAR(65535) NOT NULL,
		`URL` VARCHAR(65535) NOT NULL,
		`PASSWORD` VARCHAR(65535) NOT NULL,
		`HTML` LONGTEXT NOT NULL,
        `CREATED` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        PRIMARY KEY(ID)
    );